{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Chapter 13: Exceptions\n",
    "=============================\n",
    "_____________________________\n",
    "When a failure occurs in the program (such as division by zero, etc) at runtime, an exception is generated. If the exception is not handled, it will be propagated through function calls to the main program module, interrupting execution."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```python\n",
    "print(10/0)\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Output:**\n",
    "```python\n",
    "---------------------------------------------------------------------------\n",
    "ZeroDivisionError                         Traceback (most recent call last)\n",
    "<ipython-input-1-fe01563e1bc6> in <module>\n",
    "----> 1 print(10/0)\n",
    "\n",
    "ZeroDivisionError: division by zero\n",
    "    ```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The *try* instruction allows exception handling in Python. If an exception occurs in a block marked by *try*, it is possible to handle the exception through the instruction *except*. It is possible to have many *except* blocks for the same *try* block."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    print (1/0)\n",
    "except ZeroDivisionError as zde:\n",
    "    print('Error:', zde)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    print (1/0)\n",
    "except Exception as e:\n",
    "    print ('Error:', e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```python\n",
    "try:\n",
    "    raise Exception\n",
    "    print (1/0)\n",
    "except ZeroDivisionError:\n",
    "    print ('Error trying to divide by zero.')\n",
    "    \n",
    "```\n",
    "**Output:**\n",
    "```\n",
    "---------------------------------------------------------------------------\n",
    "Exception                                 Traceback (most recent call last)\n",
    "<ipython-input-6-39351026b008> in <module>\n",
    "      1 try:\n",
    "----> 2     raise Exception\n",
    "      3     print (1/0)\n",
    "      4 except ZeroDivisionError:\n",
    "      5     print ('Error trying to divide by zero.')\n",
    "\n",
    "Exception: \n",
    "    ```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "> **NOTE**\n",
    "><hr>\n",
    "> If *except* receives the name of an exception, only that exception will be handled. If no exception name is passed as a parameter, all exceptions will be handled."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "... TESTing.. \n",
      "Could not convert data to an integer. Test Exception\n",
      "Raise the old exception again, and exiting out..\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "try:\n",
    "    print(\"... TESTing.. \")\n",
    "    with open('myfile.txt', \"w\") as myFile:\n",
    "        for a in [\"a\", \"b\", \"c\"]:\n",
    "            myFile.write(a)\n",
    "#         for a in [\"1\", \"2\", \"3\", \"4\", \"5\", 6]:\n",
    "        for a in [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\"]:\n",
    "            myFile.write(a)\n",
    "    raise ValueError(\"Test Exception\")\n",
    "    raise NotImplemented(\"Sorry the code is still missing,\\nas developer is taking a break...\")\n",
    "except OSError as err:\n",
    "    print(\"OS error: {0}\".format(err))\n",
    "except ValueError as ve:\n",
    "    print(\"Could not convert data to an integer.\", ve)\n",
    "    print(\"Raise the old exception again, and exiting out..\")\n",
    "#     raise   # Reraising the exception.\n",
    "except:\n",
    "    print(\"Unexpected error:\", sys.exc_info())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected TypeError error: (<class 'TypeError'>, TypeError(\"unsupported operand type(s) for /: 'int' and 'str'\"), <traceback object at 0x106f6e640>)\n"
     ]
    }
   ],
   "source": [
    "# Multiple types of exceptions in single \"except\"\n",
    "import sys\n",
    "\n",
    "try:\n",
    "    a = \"Ja\"\n",
    "#     print(1 > z)\n",
    "    print(1 / a)\n",
    "except (OSError, NameError, ValueError, ZeroDivisionError) as err:\n",
    "    print(\"Some common error: {0}\".format(err))\n",
    "except TypeError:\n",
    "    print(\"Unexpected TypeError error:\", sys.exc_info())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 >  asdf\n",
      "\n",
      "2 >  asdfdfa\n",
      "\n",
      "3 >  sas\n",
      "\n",
      "An error happened:\n",
      " Traceback (most recent call last):\n",
      "  File \"<ipython-input-5-948fe50a4b22>\", line 17, in <module>\n",
      "    raise ValueError(\"Custom Error Message\")\n",
      "ValueError: Custom Error Message\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "Created on Fri Aug  5 08:50:42 2016\n",
    "\n",
    "@author: mayankjohri@gmail.com\n",
    "\"\"\"\n",
    "import traceback\n",
    "\n",
    "# Try to get a file name\n",
    "try:\n",
    "#     fn = input('File Name (temp.txt): ').strip()\n",
    "    fn = \"temp.txt\"\n",
    "    # Numbering lines\n",
    "    for i, s in enumerate(open(fn)):\n",
    "        print( i + 1,\"> \", s,)\n",
    "        if i == 2:\n",
    "            raise ValueError(\"Custom Error Message\")\n",
    "# If an error happens\n",
    "except Exception as e:\n",
    "    trace = traceback.format_exc()\n",
    "    # Show it on the screen\n",
    "    print ('An error happened:\\n', trace)\n",
    "    # And save it on a file \n",
    "    with open(\"trace_asd.log\", \"a\") as file:\n",
    "        file.write(trace)\n",
    "        file.write(f\"Error Message: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 >  asdf\n",
      "\n",
      "2 >  asdfdfa\n",
      "\n",
      "3 >  sas\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "Saving to log using print_exc\n",
    "\n",
    "@author: mayankjohri@gmail.com\n",
    "\"\"\"\n",
    "import traceback\n",
    "\n",
    "# Try to get a file name\n",
    "try:\n",
    "#     fn = input('File Name (temp.txt): ').strip()\n",
    "    fn = \"temp.txt\"\n",
    "    # Numbering lines\n",
    "    for i, s in enumerate(open(fn)):\n",
    "        print( i + 1,\"> \", s,)\n",
    "        if i == 2:\n",
    "            raise ValueError\n",
    "    \n",
    "# If an error happens\n",
    "except:\n",
    "    # And save it on a file \n",
    "    with open(\"trace_asd.log\", \"a\") as file:\n",
    "        traceback.print_exc(file=file)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The module *traceback* offers functions for dealing with error messages. The function format_exc() returns the output of the last exception formatted in a *string*.\n",
    "\n",
    "The handling of exceptions may have an *else* block, which will be executed when no exception occurs and a *finally* block, which will be executed anyway, whether an exception occurred or <span class=\"note\" title=\"The finally declaration may be used for freeing resources that were used in the try block, such as database connections or open files.\">not</span>. New types of exceptions may be defined through inheritance of the class *Exception*.\n",
    "\n",
    "Since version 2.6, the instruction *with* is available, that may replace the combination of *try / finally* in many situations. It is possible to define an object that will be used during the *with* block execution. The object will support the context management protocol, which means that it will need to have an `__enter__()` method, which will be executed at the beginning of the block, and another called `__exit__()`, which will be called at the end of the block.\n",
    "\n",
    "Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Testing\n",
      "Doing some stuff and will now raise error\n",
      "reverting the changes as following exception happend\n",
      "\t A very specific bad thing happened\n",
      "Exiting out\n"
     ]
    }
   ],
   "source": [
    "def do_some_stuff():\n",
    "    print(\"Doing some stuff\")\n",
    "\n",
    "def do_some_stuff_e():\n",
    "    print(\"Doing some stuff and will now raise error\")\n",
    "    raise ValueError('A very specific bad thing happened')\n",
    "\n",
    "def rollback(e):\n",
    "    print(\"reverting the changes as following exception happend\")\n",
    "    print(\"\\t\", e)\n",
    "\n",
    "def commit():\n",
    "    print(\"commiting the changes\")\n",
    "    \n",
    "print(\"Testing\")\n",
    "\n",
    "try:\n",
    "#     do_some_stuff()\n",
    "    do_some_stuff_e()\n",
    "except Exception as e:\n",
    "    # add some code for tracelog also.\n",
    "    rollback(e)\n",
    "else:\n",
    "    commit()\n",
    "finally:\n",
    "    print(\"Exiting out\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Execution Flow\n",
    "# ----------------\n",
    "# #### ERROR Condtion\n",
    "# Testing\n",
    "#     try block\n",
    "# Doing some stuff and will now raise error\n",
    "#     except block\n",
    "# reverting the changes\n",
    "#     Finally block\n",
    "# Exiting out\n",
    "\n",
    "# NO ERROR\n",
    "# Testing\n",
    "#     Try block\n",
    "# Doing some stuff\n",
    "#     else block\n",
    "# commiting the changes\n",
    "#     finally block\n",
    "# Exiting out"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Writing Exception Classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Host Not Found exception: missing gitpub.com\n",
      "gitpub.com\n"
     ]
    }
   ],
   "source": [
    "class HostNotFound(Exception):\n",
    "    def __init__( self, host):\n",
    "        self.host = host\n",
    "        Exception.__init__(self, 'Host Not Found exception: missing %s' % host)\n",
    "\n",
    "try:\n",
    "    raise HostNotFound(\"gitpub.com\")\n",
    "except HostNotFound as hcf:\n",
    "    # Handle exception.\n",
    "    print (hcf)  # -> 'Host Not Found exception: missing taoriver.net'\n",
    "    print (hcf.host)  # -> 'gitpub.com'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": true
   },
   "source": [
    "> **Note:**\n",
    "> ___\n",
    "> Normally its not recommended to create your own exception class"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: can't find file or read data\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    fh = open(\"nonexisting.txt\", \"r\")\n",
    "    try:\n",
    "        fh.write(\"This is my test file for exception handling!!\")\n",
    "        print(1/0)\n",
    "    except:\n",
    "        print(\"Caught error message\")\n",
    "    finally:\n",
    "        print (\"Going to close the file\")\n",
    "        fh.close()\n",
    "except IOError:\n",
    "    print (\"Error: can\\'t find file or read data\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Caught error message\n",
      "Going to close the file\n",
      "Error: can't find file or read data\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "#     fh = open(\"nonexisting.txt\", \"r\")\n",
    "    try:\n",
    "        fh.write(\"This is my test file for exception handling!!\")\n",
    "        print(1/0)\n",
    "    except:\n",
    "        print(\"Caught error message\")\n",
    "        raise\n",
    "    finally:\n",
    "        print (\"Going to close the file\")\n",
    "        fh.close()\n",
    "except:\n",
    "    print (\"Error: can\\'t find file or read data\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```python\n",
    "try:\n",
    "    try:\n",
    "        print(1/0)\n",
    "    except:\n",
    "        print(\"Caught error message\") \n",
    "    finally:\n",
    "        print (\"Going to close the file\")\n",
    "    print(1/0)\n",
    "except :\n",
    "    print (\"Error: can\\'t find file or read data\")\n",
    "    raise\n",
    "```\n",
    "**Output:**\n",
    "```python\n",
    "Caught error message\n",
    "Going to close the file\n",
    "Error: can't find file or read data\n",
    "---------------------------------------------------------------------------\n",
    "ZeroDivisionError                         Traceback (most recent call last)\n",
    "<ipython-input-12-5286be6ebe6e> in <module>\n",
    "      9         print (\"Going to close the file\")\n",
    "     10 #         fh.close()print(1/0)\n",
    "---> 11     print(1/0)\n",
    "     12 except :\n",
    "     13     print (\"Error: can\\'t find file or read data\")\n",
    "\n",
    "ZeroDivisionError: division by zero\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello\n",
      "In Finally\n"
     ]
    }
   ],
   "source": [
    "# Valid construct, but why you will use it. :(\n",
    "\n",
    "try:\n",
    "    print(\"Hello\")\n",
    "finally:\n",
    "    print(\"In Finally\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Exception hierarchy\n",
    "\n",
    "The class hierarchy for built-in exceptions is:\n",
    "\n",
    "```\n",
    "BaseException\n",
    " +-- SystemExit\n",
    " +-- KeyboardInterrupt\n",
    " +-- GeneratorExit\n",
    " +-- Exception\n",
    "      +-- StopIteration\n",
    "      +-- StopAsyncIteration\n",
    "      +-- ArithmeticError\n",
    "      |    +-- FloatingPointError\n",
    "      |    +-- OverflowError\n",
    "      |    +-- ZeroDivisionError\n",
    "      +-- AssertionError\n",
    "      +-- AttributeError\n",
    "      +-- BufferError\n",
    "      +-- EOFError\n",
    "      +-- ImportError\n",
    "      +-- LookupError\n",
    "      |    +-- IndexError\n",
    "      |    +-- KeyError\n",
    "      +-- MemoryError\n",
    "      +-- NameError\n",
    "      |    +-- UnboundLocalError\n",
    "      +-- OSError\n",
    "      |    +-- BlockingIOError\n",
    "      |    +-- ChildProcessError\n",
    "      |    +-- ConnectionError\n",
    "      |    |    +-- BrokenPipeError\n",
    "      |    |    +-- ConnectionAbortedError\n",
    "      |    |    +-- ConnectionRefusedError\n",
    "      |    |    +-- ConnectionResetError\n",
    "      |    +-- FileExistsError\n",
    "      |    +-- FileNotFoundError\n",
    "      |    +-- InterruptedError\n",
    "      |    +-- IsADirectoryError\n",
    "      |    +-- NotADirectoryError\n",
    "      |    +-- PermissionError\n",
    "      |    +-- ProcessLookupError\n",
    "      |    +-- TimeoutError\n",
    "      +-- ReferenceError\n",
    "      +-- RuntimeError\n",
    "      |    +-- NotImplementedError\n",
    "      |    +-- RecursionError\n",
    "      +-- SyntaxError\n",
    "      |    +-- IndentationError\n",
    "      |         +-- TabError\n",
    "      +-- SystemError\n",
    "      +-- TypeError\n",
    "      +-- ValueError\n",
    "      |    +-- UnicodeError\n",
    "      |         +-- UnicodeDecodeError\n",
    "      |         +-- UnicodeEncodeError\n",
    "      |         +-- UnicodeTranslateError\n",
    "      +-- Warning\n",
    "           +-- DeprecationWarning\n",
    "           +-- PendingDeprecationWarning\n",
    "           +-- RuntimeWarning\n",
    "           +-- SyntaxWarning\n",
    "           +-- UserWarning\n",
    "           +-- FutureWarning\n",
    "           +-- ImportWarning\n",
    "           +-- UnicodeWarning\n",
    "           +-- BytesWarning\n",
    "           +-- ResourceWarning\n",
    "\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(object, ()), [(BaseException, (object,)), [(Exception, (BaseException,))]]]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import inspect\n",
    "inspect.getclasstree(inspect.getmro(Exception))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " BaseException\n",
      "... Exception\n",
      "...... TypeError\n",
      "......... MultipartConversionError\n",
      "......... FloatOperation\n",
      "...... StopAsyncIteration\n",
      "...... StopIteration\n",
      "...... ImportError\n",
      "......... ModuleNotFoundError\n",
      "......... ZipImportError\n",
      "...... OSError\n",
      "......... ConnectionError\n",
      "............ BrokenPipeError\n",
      "............ ConnectionAbortedError\n",
      "............ ConnectionRefusedError\n",
      "............ ConnectionResetError\n",
      "............... RemoteDisconnected\n",
      "......... BlockingIOError\n",
      "......... ChildProcessError\n",
      "......... FileExistsError\n",
      "......... FileNotFoundError\n",
      "......... IsADirectoryError\n",
      "......... NotADirectoryError\n",
      "......... InterruptedError\n",
      "............ InterruptedSystemCall\n",
      "......... PermissionError\n",
      "......... ProcessLookupError\n",
      "......... TimeoutError\n",
      "......... UnsupportedOperation\n",
      "......... ItimerError\n",
      "......... Error\n",
      "............ SameFileError\n",
      "......... SpecialFileError\n",
      "......... ExecError\n",
      "......... ReadError\n",
      "......... herror\n",
      "......... gaierror\n",
      "......... timeout\n",
      "......... SSLError\n",
      "............ SSLCertVerificationError\n",
      "............ SSLZeroReturnError\n",
      "............ SSLWantReadError\n",
      "............ SSLWantWriteError\n",
      "............ SSLSyscallError\n",
      "............ SSLEOFError\n",
      "......... URLError\n",
      "............ HTTPError\n",
      "............ ContentTooShortError\n",
      "...... EOFError\n",
      "......... IncompleteReadError\n",
      "...... RuntimeError\n",
      "......... RecursionError\n",
      "......... NotImplementedError\n",
      "............ StdinNotImplementedError\n",
      "............ ZMQVersionError\n",
      "......... _DeadlockError\n",
      "......... BrokenBarrierError\n",
      "......... BrokenExecutor\n",
      "......... SendfileNotAvailableError\n",
      "...... NameError\n",
      "......... UnboundLocalError\n",
      "...... AttributeError\n",
      "...... SyntaxError\n",
      "......... IndentationError\n",
      "............ TabError\n",
      "...... LookupError\n",
      "......... IndexError\n",
      "......... KeyError\n",
      "............ UnknownBackend\n",
      "............ NoSuchKernel\n",
      "......... CodecRegistryError\n",
      "...... ValueError\n",
      "......... UnicodeError\n",
      "............ UnicodeEncodeError\n",
      "............ UnicodeDecodeError\n",
      "............ UnicodeTranslateError\n",
      "......... UnsupportedOperation\n",
      "......... JSONDecodeError\n",
      "......... ClassNotFound\n",
      "......... Error\n",
      "......... SSLCertVerificationError\n",
      "......... ClipboardEmpty\n",
      "......... MessageDefect\n",
      "............ NoBoundaryInMultipartDefect\n",
      "............ StartBoundaryNotFoundDefect\n",
      "............ CloseBoundaryNotFoundDefect\n",
      "............ FirstHeaderLineIsContinuationDefect\n",
      "............ MisplacedEnvelopeHeaderDefect\n",
      "............ MissingHeaderBodySeparatorDefect\n",
      "............ MultipartInvariantViolationDefect\n",
      "............ InvalidMultipartContentTransferEncodingDefect\n",
      "............ UndecodableBytesDefect\n",
      "............ InvalidBase64PaddingDefect\n",
      "............ InvalidBase64CharactersDefect\n",
      "............ InvalidBase64LengthDefect\n",
      "............ HeaderDefect\n",
      "............... InvalidHeaderDefect\n",
      "............... HeaderMissingRequiredValue\n",
      "............... NonPrintableDefect\n",
      "............... ObsoleteHeaderDefect\n",
      "............... NonASCIILocalPartDefect\n",
      "......... IllegalMonthError\n",
      "......... IllegalWeekdayError\n",
      "......... MacroToEdit\n",
      "...... AssertionError\n",
      "...... ArithmeticError\n",
      "......... FloatingPointError\n",
      "......... OverflowError\n",
      "......... ZeroDivisionError\n",
      "............ DivisionByZero\n",
      "............ DivisionUndefined\n",
      "......... DecimalException\n",
      "............ Clamped\n",
      "............ Rounded\n",
      "............... Underflow\n",
      "............... Overflow\n",
      "............ Inexact\n",
      "............... Underflow\n",
      "............... Overflow\n",
      "............ Subnormal\n",
      "............... Underflow\n",
      "............ DivisionByZero\n",
      "............ FloatOperation\n",
      "............ InvalidOperation\n",
      "............... ConversionSyntax\n",
      "............... DivisionImpossible\n",
      "............... DivisionUndefined\n",
      "............... InvalidContext\n",
      "...... SystemError\n",
      "......... CodecRegistryError\n",
      "...... ReferenceError\n",
      "...... MemoryError\n",
      "...... BufferError\n",
      "...... Warning\n",
      "......... UserWarning\n",
      "............ GetPassWarning\n",
      "............ FormatterWarning\n",
      "......... DeprecationWarning\n",
      "............ ProvisionalWarning\n",
      "......... PendingDeprecationWarning\n",
      "......... SyntaxWarning\n",
      "......... RuntimeWarning\n",
      "............ UnknownTimezoneWarning\n",
      "......... FutureWarning\n",
      "............ ProvisionalCompleterWarning\n",
      "......... ImportWarning\n",
      "......... UnicodeWarning\n",
      "......... BytesWarning\n",
      "......... ResourceWarning\n",
      "......... DeprecatedTzFormatWarning\n",
      "...... Error\n",
      "...... _OptionError\n",
      "...... _Error\n",
      "...... error\n",
      "...... Verbose\n",
      "...... SubprocessError\n",
      "......... CalledProcessError\n",
      "......... TimeoutExpired\n",
      "...... TokenError\n",
      "...... StopTokenizing\n",
      "...... Error\n",
      "...... error\n",
      "...... LZMAError\n",
      "...... RegistryError\n",
      "...... EndOfBlock\n",
      "...... error\n",
      "...... TraitError\n",
      "...... ArgumentError\n",
      "...... ArgumentTypeError\n",
      "...... ConfigError\n",
      "......... ConfigLoaderError\n",
      "............ ArgumentError\n",
      "......... ConfigFileNotFound\n",
      "...... ConfigurableError\n",
      "......... MultipleInstanceError\n",
      "...... ApplicationError\n",
      "...... ErrorDuringImport\n",
      "...... BdbQuit\n",
      "...... OptionError\n",
      "...... Restart\n",
      "...... ExceptionPexpect\n",
      "......... EOF\n",
      "......... TIMEOUT\n",
      "...... error\n",
      "...... PtyProcessError\n",
      "...... FindCmdError\n",
      "...... HomeDirError\n",
      "...... ProfileDirError\n",
      "...... IPythonCoreError\n",
      "......... TryNext\n",
      "......... UsageError\n",
      "......... StdinNotImplementedError\n",
      "...... InputRejected\n",
      "...... GetoptError\n",
      "...... Incomplete\n",
      "...... ErrorToken\n",
      "...... Error\n",
      "......... CancelledError\n",
      "......... TimeoutError\n",
      "......... InvalidStateError\n",
      "...... _GiveupOnSendfile\n",
      "...... QueueEmpty\n",
      "...... QueueFull\n",
      "...... LimitOverrunError\n",
      "...... _Stop\n",
      "...... PickleError\n",
      "......... PicklingError\n",
      "......... UnpicklingError\n",
      "...... PrefilterError\n",
      "...... AliasError\n",
      "......... InvalidAliasError\n",
      "...... Error\n",
      "......... InterfaceError\n",
      "......... DatabaseError\n",
      "............ InternalError\n",
      "............ OperationalError\n",
      "............ ProgrammingError\n",
      "............ IntegrityError\n",
      "............ DataError\n",
      "............ NotSupportedError\n",
      "...... Warning\n",
      "...... SpaceInInput\n",
      "...... TaskLocalNotSetError\n",
      "...... InvalidStateError\n",
      "...... Return\n",
      "...... Empty\n",
      "...... Full\n",
      "...... NoRunningApplicationError\n",
      "...... ValidationError\n",
      "...... EditReadOnlyBuffer\n",
      "...... _Retry\n",
      "...... DOMException\n",
      "......... IndexSizeErr\n",
      "......... DomstringSizeErr\n",
      "......... HierarchyRequestErr\n",
      "......... WrongDocumentErr\n",
      "......... InvalidCharacterErr\n",
      "......... NoDataAllowedErr\n",
      "......... NoModificationAllowedErr\n",
      "......... NotFoundErr\n",
      "......... NotSupportedErr\n",
      "......... InuseAttributeErr\n",
      "......... InvalidStateErr\n",
      "......... SyntaxErr\n",
      "......... InvalidModificationErr\n",
      "......... NamespaceErr\n",
      "......... InvalidAccessErr\n",
      "......... ValidationErr\n",
      "...... InvalidLayoutError\n",
      "...... HeightIsUnknownError\n",
      "...... ParserSyntaxError\n",
      "...... InternalParseError\n",
      "...... _PositionUpdatingFinished\n",
      "...... UncaughtAttributeError\n",
      "...... SimpleGetItemNotFound\n",
      "...... ParamIssue\n",
      "...... OnErrorLeaf\n",
      "...... _JediError\n",
      "......... InternalError\n",
      "......... WrongVersion\n",
      "...... InvalidPythonEnvironment\n",
      "...... MessageError\n",
      "......... MessageParseError\n",
      "............ HeaderParseError\n",
      "............ BoundaryError\n",
      "......... MultipartConversionError\n",
      "......... CharsetError\n",
      "...... Error\n",
      "...... HTTPException\n",
      "......... NotConnected\n",
      "......... InvalidURL\n",
      "......... UnknownProtocol\n",
      "......... UnknownTransferEncoding\n",
      "......... UnimplementedFileMode\n",
      "......... IncompleteRead\n",
      "......... ImproperConnectionState\n",
      "............ CannotSendRequest\n",
      "............ CannotSendHeader\n",
      "............ ResponseNotReady\n",
      "......... BadStatusLine\n",
      "............ RemoteDisconnected\n",
      "......... LineTooLong\n",
      "...... InteractivelyDefined\n",
      "...... KillEmbedded\n",
      "...... ArgumentError\n",
      "...... ZMQBaseError\n",
      "......... ZMQError\n",
      "............ ContextTerminated\n",
      "............ Again\n",
      "............ InterruptedSystemCall\n",
      "......... ZMQBindError\n",
      "......... NotDone\n",
      "...... NoIPAddresses\n",
      "...... InvalidPortNumber\n",
      "...... DuplicateKernelError\n",
      "...... TimeoutError\n",
      "...... error\n",
      "...... ReturnValueIgnoredError\n",
      "...... KeyReuseError\n",
      "...... UnknownKeyError\n",
      "...... LeakedCallbackError\n",
      "...... BadYieldError\n",
      "...... ReturnValueIgnoredError\n",
      "...... Return\n",
      "...... QueueEmpty\n",
      "...... QueueFull\n",
      "...... HostNotFound\n",
      "... GeneratorExit\n",
      "... SystemExit\n",
      "... KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "# https://stackoverflow.com/questions/18296653/print-the-python-exception-error-hierarchy\n",
    "def classtree(cls, indent=0):\n",
    "    print ('.' * indent, cls.__name__)\n",
    "    for subcls in cls.__subclasses__():\n",
    "        classtree(subcls, indent + 3)\n",
    "\n",
    "classtree(BaseException)"
   ]
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
